
version: "3.9"
services:
  etl_app:
    # image: etl:1.0
    # command: python Controller.py
    build: .
    ports:
      - "8080:8080"
    #working_dir: /app
    volumes:
      - "./data:/app/data"

# docker compose up / down